[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# gas_limit = "18446744073709551615"

# ETH_RPC_URL=https://eth-mainnet.alchemyapi.io/v2/kIP2_euA9T6Z-e5MjHzTzRUmgqCLsHUA
# eth_rpc_url = "https://eth-mainnet.alchemyapi.io/v2/kIP2_euA9T6Z-e5MjHzTzRUmgqCLsHUA" 
eth_rpc_url = "https://eth-mainnet.alchemyapi.io/v2/kIP2_euA9T6Z-e5MjHzTzRUmgqCLsHUA" 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md
include_paths = [
"broadcast",
"cairo-auction",
"cairo-proxy",
"electric-sheep",
"fun-reversing-challenge",
"hana",
"hint-finance",
"just-in-time",
"lockbox2",
"merkledrop",
"otter-world",
"otterswap",
"pool",
"private",
"random",
"rescue",
"riddle-of-the-sphinx",
"sourcecode",
"stealing-sats",
# "test",
"trapdoooor",
"trapdooor",
"vanity",]