[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ignored_error_codes = [5667,2018,2072,1878,8760,6321,5574,9302,3628,2462,2519 ]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
# via_ir = true
allow_paths = ["../node_modules", "../src", "../test", "../lib"]