[profile.default]
src = "contracts"
out = "artifactsFoundry"
libs = ["node_modules", "lib"]
test = 'testFoundry'
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'forge-std/=lib/forge-std/src/',
    'ds-test/=node_modules/ds-test/src/',
    '@uniswap/=node_modules/@uniswap/',
    '@gearbox-protocol/=node_modules/@gearbox-protocol/',
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
ignored_error_codes = ["license", "code-size", "unused-return", "unused-param", "unused-var", "code-size", "shadowing", "func-mutability", "license", "pragma-solidity", "virtual-interfaces", "same-varname",2018,5667,2072,3420,2519]
# deny_warnings = true


[fmt]
bracket_spacing = true
number_underscore = "thousands"

[profile.test]
src = 'testFoundry'

