[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.13"
evm_version = "shanghai"
optimizer = false

fs_permissions = [{ access = 'read-write', path = '/'}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# http://164.90.231.253:8545/tVOAezAwJVwMTNBXsyiPTfie/main

eth_rpc_url = "http://164.90.231.253:8545/tVOAezAwJVwMTNBXsyiPTfie/main"

