[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
  mainnet = "https://sonic-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"

eth_rpc_url = "https://sonic-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"