[profile.default]
src = 'contracts'
test = 'test/foundry'
out = 'out'
libs = ['lib']
no_match_path = "contracts/*"
solc_version = '0.8.25'
optimizer = true
optimizer_runs = 1
viaIR = false
eth_rpc_url = "https://eth-mainnet.g.alchemy.com/v2/kIP2_euA9T6Z-e5MjHzTzRUmgqCLsHUA"

# RINKEBY_URL=https://eth-rinkeby.alchemyapi.io/v2/PgIMBvYWNcJqp_DLeGahPoWNMAHWfHSv
# MAINNET_URL=https://eth-mainnet.alchemyapi.io/v2/kIP2_euA9T6Z-e5MjHzTzRUmgqCLsHUA
# ARBITRUM_URL=https://arb-mainnet.g.alchemy.com/v2/PxqMNBxAITOvMuJn_KmVI8XtGj337Arm
# POLYGON_URL=https://polygon-mainnet.g.alchemy.com/v2/hKJpr5g9diR6_ncuOv7Fv7h4S4EexQgy
# OPTIMISM_URL=https://opt-mainnet.g.alchemy.com/v2/PwLgjh_gVinp6KpZENosOzc20pGeLKdD
# GOERLI_URL=https://eth-goerli.alchemyapi.io/v2/q5Y2SBMlUiVd7ByoUkIjrruq9adhjUFz
[profile.ci_test]
fork_block_number = 18963715

[profile.ci_sizes]
optimizer_runs = 1
test = 'DO_NOT_COMPILE'

[profile.ci_sizes_ir]
optimizer_runs = 200
test = 'DO_NOT_COMPILE'
viaIR = true

[fuzz]
runs = 5000
max_test_rejects = 20000