# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# viaIR = true 
optimizer_runs = 1_000_000
# ETH_RPC_URL="https://eth-mainnet.alchemyapi.io/v2/kIP2_euA9T6Z-e5MjHzTzRUmgqCLsHUA"
eth_rpc_url = "https://eth-mainnet.alchemyapi.io/v2/kIP2_euA9T6Z-e5MjHzTzRUmgqCLsHUA"
block_number=19722400
fork_block_number=19722400
etherscan_api_key = "64D8FMTIH1UG2BCD2A1BFMFZCTF6S2YG95"

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true