[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = 'read-write', path = '/'}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# eth_rpc_url = "http://159.223.19.251:8545/qmhUFCfIGNrhQnlzjNwNtFju/main"
