[package]
name = "AaveData"
#version = "1.0.0"
#upgrade_policy = "compatible"
authors = []

[addresses]
# aave_data = "_"
# aave_oracle_racc_address = '_'
# data_feeds = '_'
# platform = '_'
aave_pool = '0x39ddcd9e1a39fa14f25e3f9ec8a86074d05cc0881cbf667df8a6ee70942016fb'
aave_acl = '0x34c3e6af238f3a7fa3f3b0088cbc4b194d21f62e65a15b79ae91364de5a81a3a'
aave_config = '0x531069f4741cdead39d70b76e5779863864654fae6db8a752a244ff2f9916c15'
aave_math = '0xc0338eea778de2a5348824ddbfcec033c7f7cbe18da6da40869562906b63c78c'
aave_mock_underlyings = '0x12b05c42ac3209a3c6ffadff4ebb6c3e983e5115f26031d56652815b49a14245'
aave_oracle = '0x249676f3faddb83d64fd101baa3f84a171ae02505d796e3edbf4861038a4b5cc'
aave_data = '0x5eb5cc775c5a446db0f3a1c944e11563b97e6a7e1387b9fb459aa26168f738dc'
aave_oracle_racc_address = '0xe84c8f7bbd3d0700f4a2cc406800751bb6f6ca643052c1565a7f55304ba960ca'
data_feeds = '0x100'
platform = '0x200'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
AaveAcl = { local = "../aave-acl" }
AaveConfig = { local = "../aave-config" }
AaveMath = { local = "../aave-math" }
AaveOracle = { local = "../aave-oracle" }
AavePool = { local = "../" }

