[profile.default]
src = 'contracts'
test = 'forge-tests'
out = 'artifactsforge'
cache = false
gas_reports = ["*"]
lib = ['forge-tests/lib']
remappings = [
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'forge-tests/=forge-tests',
    'lib/=lib/'
]
fs_permissions = [{ access = "read", path = "./artifactsforge"}]
libs = ["node_modules", "lib"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
eth_rpc_url = "https://eth-mainnet.alchemyapi.io/v2/kIP2_euA9T6Z-e5MjHzTzRUmgqCLsHUA"
# block_number = 19558000
fork_block_number = 19558000

# [fuzz]
# runs = 5000
# max_test_rejects = 65536